module.exports = {
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.ts"],
  preset: "ts-jest",
  testEnvironment: "jsdom",
  transform: {
    "^.+\\.tsx?$": "ts-jest",
    "^.+\\.jsx?$": "babel-jest",
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  moduleNameMapper: {
    "\\.(css|less)$": "<rootDir>/src/__mocks__/styleMock.cjs",
    "\\.(jpg|jpeg|png|gif|svg)$": "<rootDir>/src/__mocks__/fileMock.cjs",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@pages/(.*)$": "<rootDir>/src/pages/$1",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@constants$": "<rootDir>/src/constants/index",
    "^@constants/(.*)$": "<rootDir>/src/constants/$1",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@services/(.*)$": "<rootDir>/src/services/$1",
    "^@admin/(.*)$": "<rootDir>/src/admin/$1",
    "^@super-admin/(.*)$": "<rootDir>/src/super-admin/$1",
    "^@user/(.*)$": "<rootDir>/src/user/$1",
    "^@landing/(.*)$": "<rootDir>/src/landing/$1",
    "^@interfaces/(.*)$": "<rootDir>/src/interfaces/$1",
    "^@common/(.*)$": "<rootDir>/src/components/common/$1",
    "^@UI/(.*)$": "<rootDir>/src/components/UI/$1",
    "^@atoms/(.*)$": "<rootDir>/src/atoms/$1",
    "^@forms/(.*)$": "<rootDir>/src/forms/$1",
  },
  transformIgnorePatterns: [
    "node_modules/(?!(some-esm-package|another-esm-package)/)",
  ],
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/*.spec.{ts,tsx}",
    "!src/**/__tests__/**",
    "!src/main.tsx",
    "!src/vite-env.d.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "text-summary", "html", "lcov"],
};
