// export const data: any = [
//   {
//     project_id: "Srytal",
//     acitivities: {
//       task_id: "Task details",
//       workingDays: {
//         month: {
//           "11": {
//             day: {
//               "1": {
//                 hours: 4,
//                 task: "task details",
//               },
//               "2": {
//                 hours: 8,
//                 task: "task details on this day",
//               },
//               "3": {
//                 hours: 2,
//                 task: "WEEK_OFF",
//               },
//             },
//           },
//         },
//       },
//     },
//   },
//   {
//     project_id: "Data",
//     acitivities: {
//       workingDays: {
//         month: {
//           "11": {
//             day: {
//               "1": {
//                 hours: 4,
//                 task: "task details",
//               },
//               "2": {
//                 hours: 0,
//                 task: "task details on this day",
//               },
//               "3": {
//                 hours: 6,
//                 task: "WEEK_OFF",
//               },
//             },
//           },
//         },
//       },
//     },
//   },
// ];

export const data = [
  // Project 1 - Web Development
  {
    date: '01-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1001',
    task_id: 'T1001',
    project_name: 'Website Redesign',
    task_name: 'Frontend Development',
    hours: 4,
  },
  {
    date: '01-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1001',
    task_id: 'T1002',
    project_name: 'Website Redesign',
    task_name: 'Backend API',
    hours: 3,
  },
  {
    date: '01-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1001',
    task_id: 'T1003',
    project_name: 'Website Redesign',
    task_name: 'Database Design',
    hours: 1,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1001',
    task_id: 'T1001',
    project_name: 'Website Redesign',
    task_name: 'Frontend Development',
    hours: 6,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1001',
    task_id: 'T1002',
    project_name: 'Website Redesign',
    task_name: 'Backend API',
    hours: 2,
  },
  {
    date: '03-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: true,
    project_id: 'P1001',
    task_id: 'T1001',
    project_name: 'Website Redesign',
    task_name: 'Frontend Development',
    hours: 0,
  },

  // Project 2 - Mobile App
  {
    date: '01-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1002',
    task_id: 'T2001',
    project_name: 'Mobile App',
    task_name: 'UI Design',
    hours: 2,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1002',
    task_id: 'T2001',
    project_name: 'Mobile App',
    task_name: 'UI Design',
    hours: 3,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1002',
    task_id: 'T2002',
    project_name: 'Mobile App',
    task_name: 'API Integration',
    hours: 5,
  },
  {
    date: '03-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: true,
    project_id: 'P1002',
    task_id: 'T2003',
    project_name: 'Mobile App',
    task_name: 'Testing',
    hours: 0,
  },
  {
    date: '04-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1002',
    task_id: 'T2003',
    project_name: 'Mobile App',
    task_name: 'Testing',
    hours: 7,
  },

  // Project 3 - Marketing
  {
    date: '01-06-2025',
    isLeave: true,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1003',
    task_id: 'T3001',
    project_name: 'Marketing Campaign',
    task_name: 'Content Creation',
    hours: 0,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1003',
    task_id: 'T3001',
    project_name: 'Marketing Campaign',
    task_name: 'Content Creation',
    hours: 4,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1003',
    task_id: 'T3002',
    project_name: 'Marketing Campaign',
    task_name: 'Social Media',
    hours: 3,
  },
  {
    date: '03-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: true,
    project_id: 'P1003',
    task_id: 'T3002',
    project_name: 'Marketing Campaign',
    task_name: 'Social Media',
    hours: 0,
  },
  {
    date: '04-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1003',
    task_id: 'T3003',
    project_name: 'Marketing Campaign',
    task_name: 'Email Campaign',
    hours: 6,
  },

  // Project 4 - Internal
  {
    date: '01-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1004',
    task_id: 'T4001',
    project_name: 'Internal Training',
    task_name: 'React Workshop',
    hours: 8,
  },
  {
    date: '02-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1004',
    task_id: 'T4002',
    project_name: 'Internal Training',
    task_name: 'Database Optimization',
    hours: 3,
  },
  {
    date: '03-06-2025',
    isLeave: false,
    isHoliday: false,
    isWeekOff: false,
    project_id: 'P1004',
    task_id: 'T4002',
    project_name: 'Internal Training',
    task_name: 'Database Optimization',
    hours: 0,
  },
  {
    date: '06-06-2025',
    isLeave: true,
    isHoliday: false,
    isWeekOff: false,
    project_id: '',
    task_id: '',
    project_name: '',
    task_name: '',
    hours: 5,
  },
];
